function actor_on_first_update()
	if has_alife_info("raid_shelter_objects_spawned") and not has_alife_info("raid_liaison_spawned") then
		local smart = SIMBOARD.smarts_by_names["rad2_prip_teleport"]
		if smart then
			SIMBOARD:create_squad(smart, "raid_liaison_squad")
		end
		give_info("raid_liaison_spawned")
	end
end

function on_game_start()
	RegisterScriptCallback("actor_on_first_update", actor_on_first_update)
end